sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install pytest
- pip install coveralls
language: python
script:
 - flake8 PyXiaomiGateway --max-line-length=120
 - pylint PyXiaomiGateway --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: DQvNzatG4iBuvoKmc+eTL3mJnd+DHa/qJa24w8jVjppDY9A69G/bUsHuQvvMrbWSBTlXykMRqr3jIM9Vch/GK4o4DmMwfvxXfTSU8M9WJzRJ+AI3m05MO/tq3BUyiNp3zNyXJUq2QEVUT5utnYCFWB0CioUrFjD15cVVoyIRhQE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/PyXiaomiGateway
