sudo: required
language: python
python:
- '3.5'
cache: pip
install:
- sudo modprobe dummy
- sudo ip addr add 10.0.0.1/29 dev dummy0
- sudo ip link set dummy0 up
- sudo ifconfig dummy0:0 10.0.0.2 netmask 255.255.255.248
- sudo ifconfig dummy0:1 10.0.0.3 netmask 255.255.255.248
- ifconfig
- pip install flake8 pylint cryptography==2.1.1 asyncio pytest==5.4.3 pytest-asyncio
script:
- flake8 xiaomi_gateway --max-line-length=120
- pylint xiaomi_gateway --max-line-length=120
- pytest
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: BToqJKqsbxAPksYx9TCZur5RqgJi5/FIKm3OtQ5k7q95fEiqU3RGOCDbfkw4lk7bq3lzDRvp9Ml1JuwRb2VFm6DMSp66XaybqKAiKGJxuR1AtcmQpJ/jmHGGbAP2WsFNTx/sjpoymm2U6VZUZmD758LReiTCMMu2WmtpaSCgXfK3MOn5PBIYAM5AMKAaU8BYXj6VmOPYKdqDhWm1isPMJTVB+sFiuvWwNv9bpsBn/GpEeB2AFqHFmV+LmPwDKDbGIS+I/WPfhBF9YVncGNtp9IMQVKyaeMq6XUv8pfFPfs/oBYEK4u1Xg+NpRPKlWf8d8Hjx2W/lKyDiPpCaW8S+HRxB6Jl9ZWt0FwEa1k9BSIXdZgAPHdx1ExXI9UJk54iMxDxAfCJ8aXvMy4hIByO7HR8wtu1OJhR2BfBIsom0rRYBg2JhjHv0ufbkOxk6NpZoTIQa+3Syri8C0hbi/3HxkRjwwGIs/nDSHQ7+vHr6B2lUDy//u3+xB5QhKbZkgiZ8TmccyCqfq267jFYiPQxSBbPgAvguHLnAnldzahShB3bmTApp4S3hui9Fz/mty74o4fHTh4X8NRkAODLwe/dw1Oe/hYB9x/vjJRHbdcabzWrhh8Z3wHhJJOe3pVjsFggep8tWcxuOaDyeu0FZObCodMqGeaokW0PHuPmTgH+uASU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/PyXiaomiGateway
