sudo: required
language: python
python:
- '3.5'
cache: pip
install:
- sudo modprobe dummy
- sudo ip addr add 10.0.0.1/29 dev dummy0
- sudo ip link set dummy0 up
- sudo ifconfig dummy0:0 10.0.0.2 netmask 255.255.255.248
- sudo ifconfig dummy0:1 10.0.0.3 netmask 255.255.255.248
- ifconfig
- pip install flake8 pylint cryptography==2.1.1 asyncio pytest==5.4.3 pytest-asyncio
script:
- flake8 xiaomi_gateway --max-line-length=120
- pylint xiaomi_gateway --max-line-length=120
- pytest
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: ZdphWu8cTWMYfUctozIy6P7bKzfAy6zq6U62AzBzXC7CgVytBCSdRnunkMSTkK5FPEVV5WRqROTNPHC8ochp2kOh7o6rOJKm2yzW5h4v1CEg5JA3wMRTayt+Gavc7eW7KqaFiRgMoAIMIgIMTpm3lmJQBLy3He7lr5J9oXGGy5DlRmjuOT9YXbRGv+4rZ2g2NNuaoBNdHMC0pzPGD0kDr1SwjfTL9RWLe2PKQ13PMrnov9M43MHhMv47kq/x8vUUc5mEySgqiJb6ulr2sVbVSmgmBs7N433DGutYPEhn0BY4AScIeXW0knRXrcrtr4IqOuQmAs7cASO7eHmjzetUCGtWyC+oKBCfpXDqYn44PqokjI9QicfTIYg0vZqptFLf408Hp3RS6H6xeQEB60Jjp3+gtjGfeOKKtjRxmKFG7z5fgZcRbrIyKJEbMNP7znBGPkI7V/tHi0slyJRmJa5yxVHWpKgjtZz1eflzEoRvoKtHt5lMVVTnohJGDDh2oQ2UCVgkljiD1oe75AseF8iLGBRoUJ5u7/HIAQJKMIS/WGn5Jg71cbRQacU/jDlrHDkQgrX0SCh0jS99oHdYW1s04EUxBnEIENE404yjCc2syHCtr367Ncry3h1tjWFbWfwf4lstannLzRdriK4dNzF9lrWmsPX0n0FNP9clrwn6eOA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/PyXiaomiGateway
